trigger:

  branches:
    include:
    - main
    - issue/*

variables:
  - name: pool-name
    value: 'Azure Pipelines'

  - name: vm-image-name
#    value: 'windows-latest' # Works on windows build agents
    value: 'ubuntu-18.04' # NU3018 error

  - name: dotnetsdk
    value: '5.0.200'
  - name: buildConfiguration
    value: 'Release'
  - name: buildPlatform
    value: 'any cpu'


stages:
  - stage: Build

    jobs:
    - job: Build
      pool:
        name: $(pool-name)
        vmImage: $(vm-image-name)
        # demands:
        # - agent.os -equals Linux

      steps:
      - checkout: self
        persistCredentials: true
        clean: true

      - task: UseDotNet@2
        displayName: 'Use .NET Core sdk $(dotnetsdk)'
        inputs:
          version: '$(dotnetsdk)'

      - task: DotNetCoreCLI@2
        displayName: dotnet restore
        inputs:
          command: restore
          projects: '**/*.csproj'
          feedsToUse: 'config'
          nugetConfigPath: 'NuGet.config'
          includeNuGetOrg: false
          verbosityRestore: minimal

